---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sdvvtqww/public_html/
    - /opt/cpanel/ea-nodejs20/bin/npm ci
    - /opt/cpanel/ea-nodejs20/bin/npm run build
    - /bin/cp -R dist/. $DEPLOYPATH
