import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      leadership: 'Leadership',
      policies: 'Policies',
      programs: 'Programs',
      impact: 'Impact',
      getInvolved: 'Get Involved',
      donate: 'Donate',
      news: 'News',
      events: 'Events',
      contact: 'Contact',
    },
    ui: {
      menu: 'Menu',
      english: 'EN',
      french: 'FR',
      donate: 'Donate',
      lightMode: 'Light Mode',
      darkMode: 'Dark Mode',
      switchToLight: 'Switch to light mode',
      switchToDark: 'Switch to dark mode',
    },
    footer: {
      text: 'A youth-focused foundation using sports, education, mentorship, and community support to build courageous futures.',
      explore: 'Explore',
      contact: 'Contact',
      email: 'Email',
      phone: 'Phone',
      address: 'Address',
      copyright: 'Copyright (c) 2026 Kevin Nambam Ninmol Foundation. All rights reserved.',
    },
    newsletter: {
      eyebrow: 'Newsletter',
      title: 'Stay updated on our impact.',
      body: 'Join our email list to receive stories, program updates, recent activities, and opportunities to support the foundation’s work.',
      note: 'Build with us over the long term through updates that show where support is making a difference.',
      placeholder: 'Enter your email address',
      subscribe: 'Subscribe',
      emailLabel: 'Email address',
      empty: 'Please enter your email address.',
      success: 'Thank you. Your newsletter signup has been captured in this placeholder flow and is ready to be connected to a live mailing system.',
    },
    credibility: {
      eyebrow: 'Credibility and Transparency',
      title: 'Built to inspire confidence among donors, partners, and institutions.',
      body: 'The foundation is committed to transparency, accountability, ethical stewardship, and responsible safeguarding practices as its work continues to grow.',
      trust: 'Trusted by communities and strengthened through visible service, practical partnerships, and responsible stewardship.',
      cta: 'Learn More About Our Governance',
    },
    floating: {
      whatsapp: 'WhatsApp Chat',
      whatsappAria: 'Chat with Kevin Nambam Ninmol Foundation on WhatsApp',
      faq: 'FAQ Assistant',
      assistantTitle: 'Foundation Assistant',
      assistantStatus: 'Online for quick guidance',
      assistantClose: 'Close assistant',
      assistantCopy: 'Ask what the foundation does, how to donate, how to volunteer, or use one of the quick topic buttons below.',
      assistantInput: 'Ask a question...',
      assistantInputLabel: 'Ask the foundation assistant a question',
      send: 'Send',
      contactFoundation: 'Contact the Foundation',
      openWhatsapp: 'Open WhatsApp',
      fallback: 'I do not have a precise answer for that yet, but I can guide you to the right page or help you contact the foundation directly on WhatsApp.',
      greeting: 'Hello. I can help with what the foundation does, how to donate, how to volunteer, and other common questions.',
    },
    home: {
      title: 'Home',
      heroEyebrow: 'Kevin Nambam Ninmol Foundation',
      heroTitle: 'Empowering Youth Through Basketball, Education, and Mentorship',
      heroText: 'We help young people choose hope over fear by opening pathways to growth, confidence, and opportunity through sport, learning, and guidance.',
      heroSupport: 'Founded from lived experience and grounded in practical service, the foundation exists to help children and youth rise above limitation and pursue brighter futures.',
      donateNow: 'Donate Now',
      joinUs: 'Join Us',
      trustAction: 'Trust through action',
      trustBody: 'Rooted in lived experience, youth mentorship, and visible community engagement in Jos and beyond.',
      impactEyebrow: 'Impact Snapshot',
      impactTitle: 'A growing record of visible, community-rooted impact.',
      impactText: 'We believe trust is built through measurable work, clear purpose, and consistent presence in the lives of young people.',
      aboutEyebrow: 'About Preview',
      aboutTitle: 'A personal story transformed into a public mission.',
      aboutText: 'Kevin Nambam Ninmol Foundation grew from a journey marked by hardship, resilience, and the life-changing power of opportunity.',
      aboutCopy: 'From a difficult beginning to national and international basketball opportunities, Kevin\'s experience now fuels a foundation committed to helping young people find hope, structure, and support for the future.',
      aboutCta: 'Learn More About Us',
      programsEyebrow: 'Programs',
      programsTitle: 'Focused programs that support learning, guidance, and youth development.',
      programsText: 'Each program area is designed to respond to real needs with practical support and long-term encouragement.',
      programsCta: 'Explore All Programs',
      featuredEyebrow: 'Featured Video',
      featuredTitle: 'See the mission in motion.',
      featuredText: 'Real footage from clinics and outreach helps supporters understand that the foundation\'s work is active, personal, and rooted in the community.',
      testimonialsEyebrow: 'Testimonials',
      testimonialsTitle: 'Stories that reflect hope, growth, and real support.',
      testimonialsText: 'These short beneficiary-style stories help visitors understand how the foundation is experienced on the ground.',
      partnersEyebrow: 'Partners & Supporters',
      partnersTitle: 'Working together to expand our impact',
      partnersText: 'The foundation grows through collaboration with schools, communities, organizations, and supporters who help make youth-focused change more practical and sustainable.',
      actionEyebrow: 'Take Action',
      actionTitle: 'Partner with us to expand hope, opportunity, and youth development.',
      actionText: 'Your donations, partnerships, and support help strengthen education access, mentoring, and practical development opportunities for young people.',
      latestActivitiesEyebrow: 'Latest Activities',
      latestActivitiesTitle: 'Live updates from outreach, mentoring, and community work.',
      latestActivitiesText: 'These recent activity snapshots show that the foundation is active, consistent, and present in the lives of the young people it serves.',
      latestUpdatesEyebrow: 'Latest Updates',
      latestUpdatesTitle: 'Recent activities and updates from the field.',
      latestUpdatesText: 'Current updates help donors, partners, and visitors see that the work is active, transparent, and ongoing.',
      newsCta: 'Visit News Page',
      heroTrustSignals: ['Trusted by communities', 'Visible outreach and local partnerships', 'Transparent, mission-led delivery'],
    },
    donatePage: {
      title: 'Donate',
      heroEyebrow: 'Donate',
      heroTitle: 'Your support creates real change',
      heroSubtitle: 'This giving page is designed to make donating simple, clear, and trustworthy for every supporter.',
      giveEyebrow: 'Give Today',
      giveTitle: 'Choose how you want to support the mission.',
      giveText: 'Your gift helps the foundation respond to practical needs through youth support, educational access, mentoring, and development initiatives across local and international giving options.',
      oneTime: 'One-time donation',
      monthly: 'Monthly donation',
      chooseCurrency: 'Choose your currency',
      currencyText: 'Base donation amounts are set in NGN and displayed automatically in your selected currency.',
      customPlaceholder: 'Enter custom amount',
      customLabel: 'Custom donation amount',
      secureTitle: 'Secure payment options',
      secureText: 'Paystack or Flutterwave can be connected here for secure one-time and monthly donations.',
      conversionNote: 'Approximate conversion:',
      transparencyEyebrow: 'Transparency',
      transparencyTitle: 'Where your money goes',
      transparencyBody: 'Every contribution is used responsibly to create measurable impact. Donations help fund direct youth support, educational materials, mentoring activities, outreach delivery, and practical development programs.',
      transparencyStatement: 'The foundation is committed to transparent stewardship so donors can understand how support is translated into practical work.',
      donorEyebrow: 'Donor Assurance',
      donorTitle: 'Giving should feel clear, secure, and trustworthy.',
      donorBody: 'The foundation is committed to responsible stewardship, clear communication, and transparent use of resources so supporters can give with confidence.',
      donorReassurance: 'Every contribution is used responsibly to create measurable impact.',
      paymentNote: 'Payment gateway placeholder: Paystack / Flutterwave',
      ctaEyebrow: 'Donate',
      ctaTitle: 'Your support creates real change',
      ctaText: 'Every donation helps extend opportunity, guidance, and practical support to young people who need it most.',
      giveNow: 'Give Now',
      donateNow: 'Donate Now',
      placeholderAlert: 'Secure payment integration placeholder.',
    },
  },
  fr: {
    nav: {
      home: 'Accueil',
      about: 'À propos',
      leadership: 'Direction',
      policies: 'Politiques',
      programs: 'Programmes',
      impact: 'Impact',
      getInvolved: 'S’impliquer',
      donate: 'Faire un don',
      news: 'Actualités',
      events: 'Événements',
      contact: 'Contact',
    },
    ui: {
      menu: 'Menu',
      english: 'EN',
      french: 'FR',
      donate: 'Faire un don',
      lightMode: 'Mode clair',
      darkMode: 'Mode sombre',
      switchToLight: 'Passer au mode clair',
      switchToDark: 'Passer au mode sombre',
    },
    footer: {
      text: 'Une fondation tournée vers la jeunesse qui utilise le sport, l’éducation, le mentorat et l’appui communautaire pour construire des avenirs courageux.',
      explore: 'Explorer',
      contact: 'Contact',
      email: 'Email',
      phone: 'Téléphone',
      address: 'Adresse',
      copyright: 'Copyright (c) 2026 Kevin Nambam Ninmol Foundation. Tous droits réservés.',
    },
    newsletter: {
      eyebrow: 'Newsletter',
      title: 'Restez informé de notre impact.',
      body: 'Inscrivez-vous à notre liste email pour recevoir des histoires, des mises à jour de programmes, des activités récentes et des occasions de soutenir le travail de la fondation.',
      note: 'Construisez avec nous sur le long terme grâce à des nouvelles qui montrent où le soutien fait la différence.',
      placeholder: 'Entrez votre adresse email',
      subscribe: 'S’abonner',
      emailLabel: 'Adresse email',
      empty: 'Veuillez entrer votre adresse email.',
      success: 'Merci. Votre inscription à la newsletter a été enregistrée dans ce flux de démonstration et peut maintenant être reliée à un système d’emailing en direct.',
    },
    credibility: {
      eyebrow: 'Crédibilité et transparence',
      title: 'Conçu pour inspirer confiance aux donateurs, partenaires et institutions.',
      body: 'La fondation s’engage en faveur de la transparence, de la responsabilité, d’une gestion éthique et de pratiques de sauvegarde responsables à mesure que son travail grandit.',
      trust: 'Approuvée par les communautés et renforcée par un service visible, des partenariats concrets et une gestion responsable.',
      cta: 'En savoir plus sur notre gouvernance',
    },
    floating: {
      whatsapp: 'Chat WhatsApp',
      whatsappAria: 'Discuter avec Kevin Nambam Ninmol Foundation sur WhatsApp',
      faq: 'Assistant FAQ',
      assistantTitle: 'Assistant de la fondation',
      assistantStatus: 'En ligne pour une orientation rapide',
      assistantClose: 'Fermer l’assistant',
      assistantCopy: 'Demandez ce que fait la fondation, comment faire un don, comment devenir bénévole, ou utilisez les boutons de sujets rapides ci-dessous.',
      assistantInput: 'Posez une question...',
      assistantInputLabel: 'Posez une question à l’assistant de la fondation',
      send: 'Envoyer',
      contactFoundation: 'Contacter la fondation',
      openWhatsapp: 'Ouvrir WhatsApp',
      fallback: 'Je n’ai pas encore de réponse précise à cela, mais je peux vous guider vers la bonne page ou vous aider à contacter directement la fondation sur WhatsApp.',
      greeting: 'Bonjour. Je peux vous aider à comprendre ce que fait la fondation, comment faire un don, comment devenir bénévole et répondre à d’autres questions courantes.',
    },
    home: {
      title: 'Accueil',
      heroEyebrow: 'Kevin Nambam Ninmol Foundation',
      heroTitle: 'Donner aux jeunes les moyens d’agir grâce au basketball, à l’éducation et au mentorat',
      heroText: 'Nous aidons les jeunes à choisir l’espoir plutôt que la peur en ouvrant des voies vers la croissance, la confiance et les opportunités par le sport, l’apprentissage et l’accompagnement.',
      heroSupport: 'Fondée sur une expérience vécue et ancrée dans un service concret, la fondation existe pour aider les enfants et les jeunes à dépasser les limites et à poursuivre un avenir meilleur.',
      donateNow: 'Faire un don',
      joinUs: 'Nous rejoindre',
      trustAction: 'La confiance par l’action',
      trustBody: 'Ancrée dans l’expérience vécue, le mentorat des jeunes et un engagement communautaire visible à Jos et au-delà.',
      impactEyebrow: 'Aperçu de l’impact',
      impactTitle: 'Un bilan croissant d’impact visible et ancré dans la communauté.',
      impactText: 'Nous croyons que la confiance se construit par un travail mesurable, une vision claire et une présence constante dans la vie des jeunes.',
      aboutEyebrow: 'Aperçu',
      aboutTitle: 'Une histoire personnelle transformée en mission publique.',
      aboutText: 'Kevin Nambam Ninmol Foundation est née d’un parcours marqué par les difficultés, la résilience et le pouvoir transformateur des opportunités.',
      aboutCopy: 'D’un début difficile à des opportunités nationales et internationales dans le basketball, l’expérience de Kevin alimente aujourd’hui une fondation engagée à aider les jeunes à trouver l’espoir, la structure et le soutien pour l’avenir.',
      aboutCta: 'En savoir plus sur nous',
      programsEyebrow: 'Programmes',
      programsTitle: 'Des programmes ciblés qui soutiennent l’apprentissage, l’accompagnement et le développement des jeunes.',
      programsText: 'Chaque domaine de programme est conçu pour répondre à des besoins réels avec un soutien pratique et un encouragement sur le long terme.',
      programsCta: 'Explorer tous les programmes',
      featuredEyebrow: 'Vidéo mise en avant',
      featuredTitle: 'Voyez la mission en mouvement.',
      featuredText: 'Des images réelles des cliniques et des actions de terrain aident les soutiens à comprendre que le travail de la fondation est actif, personnel et enraciné dans la communauté.',
      testimonialsEyebrow: 'Témoignages',
      testimonialsTitle: 'Des histoires qui reflètent l’espoir, la croissance et un vrai soutien.',
      testimonialsText: 'Ces courts témoignages de bénéficiaires aident les visiteurs à comprendre comment la fondation est vécue sur le terrain.',
      partnersEyebrow: 'Partenaires et soutiens',
      partnersTitle: 'Travailler ensemble pour élargir notre impact',
      partnersText: 'La fondation grandit grâce à la collaboration avec les écoles, les communautés, les organisations et les soutiens qui rendent le changement en faveur des jeunes plus concret et durable.',
      actionEyebrow: 'Passer à l’action',
      actionTitle: 'Partenaires avec nous pour élargir l’espoir, les opportunités et le développement des jeunes.',
      actionText: 'Vos dons, partenariats et soutiens aident à renforcer l’accès à l’éducation, le mentorat et les possibilités concrètes de développement pour les jeunes.',
      latestActivitiesEyebrow: 'Dernières activités',
      latestActivitiesTitle: 'Des nouvelles en direct des actions de terrain, du mentorat et du travail communautaire.',
      latestActivitiesText: 'Ces instantanés récents montrent que la fondation est active, constante et présente dans la vie des jeunes qu’elle accompagne.',
      latestUpdatesEyebrow: 'Dernières mises à jour',
      latestUpdatesTitle: 'Activités et nouvelles récentes du terrain.',
      latestUpdatesText: 'Les mises à jour actuelles aident les donateurs, partenaires et visiteurs à voir que le travail est actif, transparent et continu.',
      newsCta: 'Voir la page Actualités',
      heroTrustSignals: ['Approuvée par les communautés', 'Actions visibles et partenariats locaux', 'Mise en œuvre transparente et guidée par la mission'],
    },
    donatePage: {
      title: 'Faire un don',
      heroEyebrow: 'Faire un don',
      heroTitle: 'Votre soutien crée un changement réel',
      heroSubtitle: 'Cette page de don est conçue pour rendre la contribution simple, claire et digne de confiance pour chaque soutien.',
      giveEyebrow: 'Donnez aujourd’hui',
      giveTitle: 'Choisissez comment soutenir la mission.',
      giveText: 'Votre don aide la fondation à répondre à des besoins concrets à travers le soutien à la jeunesse, l’accès à l’éducation, le mentorat et les initiatives de développement, localement et à l’international.',
      oneTime: 'Don ponctuel',
      monthly: 'Don mensuel',
      chooseCurrency: 'Choisissez votre devise',
      currencyText: 'Les montants de base sont définis en NGN et s’affichent automatiquement dans la devise choisie.',
      customPlaceholder: 'Entrez un montant personnalisé',
      customLabel: 'Montant de don personnalisé',
      secureTitle: 'Options de paiement sécurisées',
      secureText: 'Paystack ou Flutterwave peuvent être connectés ici pour des dons ponctuels et mensuels sécurisés.',
      conversionNote: 'Conversion approximative :',
      transparencyEyebrow: 'Transparence',
      transparencyTitle: 'À quoi sert votre don',
      transparencyBody: 'Chaque contribution est utilisée de manière responsable pour créer un impact mesurable. Les dons financent le soutien direct aux jeunes, le matériel éducatif, le mentorat, les actions de terrain et les programmes de développement.',
      transparencyStatement: 'La fondation s’engage à une gestion transparente afin que les donateurs puissent comprendre comment le soutien se transforme en actions concrètes.',
      donorEyebrow: 'Assurance donateur',
      donorTitle: 'Donner doit être clair, sûr et digne de confiance.',
      donorBody: 'La fondation s’engage en faveur d’une gestion responsable, d’une communication claire et d’un usage transparent des ressources afin que les soutiens puissent donner en toute confiance.',
      donorReassurance: 'Chaque contribution est utilisée de manière responsable pour créer un impact mesurable.',
      paymentNote: 'Passerelle de paiement placeholder : Paystack / Flutterwave',
      ctaEyebrow: 'Faire un don',
      ctaTitle: 'Votre soutien crée un changement réel',
      ctaText: 'Chaque don aide à élargir les opportunités, l’accompagnement et le soutien concret aux jeunes qui en ont le plus besoin.',
      giveNow: 'Donner maintenant',
      donateNow: 'Faire un don',
      placeholderAlert: 'Intégration sécurisée du paiement en cours.',
    },
  },
};

const LanguageContext = createContext(null);

function getValue(obj, path) {
  return path.split('.').reduce((current, key) => current?.[key], obj);
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'en');

  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem('language', language);
  }, [language]);

  const value = useMemo(() => {
    const t = (path) => getValue(translations[language], path) ?? getValue(translations.en, path) ?? path;
    return { language, setLanguage, t };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
