import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      leadership: 'Leadership',
      policies: 'Policies',
      programs: 'Programs',
      impact: 'Impact',
      getInvolved: 'Get Involved',
      donate: 'Donate',
      news: 'News',
      events: 'Events',
      contact: 'Contact',
    },
    ui: {
      menu: 'Menu',
      more: 'More',
      english: 'EN',
      french: 'FR',
      donate: 'Donate',
      lightMode: 'Light Mode',
      darkMode: 'Dark Mode',
      switchToLight: 'Switch to light mode',
      switchToDark: 'Switch to dark mode',
      learnMore: 'Learn more',
      comingSoon: 'Coming soon',
    },
    footer: {
      text: 'A youth-focused foundation using sports, education, mentorship, and community support to build courageous futures.',
      explore: 'Explore',
      contact: 'Contact',
      email: 'Email',
      phone: 'Phone',
      address: 'Address',
      copyright: 'Copyright (c) 2026 Kevin Nambam Ninmol Foundation. All rights reserved.',
    },
    newsletter: {
      eyebrow: 'Newsletter',
      title: 'Stay updated on our impact.',
      body: "Join our email list to receive stories, program updates, recent activities, and opportunities to support the foundation's work.",
      note: 'Build with us over the long term through updates that show where support is making a difference.',
      placeholder: 'Enter your email address',
      subscribe: 'Subscribe',
      emailLabel: 'Email address',
      empty: 'Please enter your email address.',
      success: 'Thank you. Your newsletter signup has been captured in this placeholder flow and is ready to be connected to a live mailing system.',
    },
    credibility: {
      eyebrow: 'Credibility and Transparency',
      title: 'Built to inspire confidence among donors, partners, and institutions.',
      body: 'The foundation is committed to transparency, accountability, ethical stewardship, and responsible safeguarding practices as its work continues to grow.',
      trust: 'Trusted by communities and strengthened through visible service, practical partnerships, and responsible stewardship.',
      cta: 'Learn More About Our Governance',
    },
    floating: {
      whatsapp: 'WhatsApp Chat',
      whatsappAria: 'Chat with Kevin Nambam Ninmol Foundation on WhatsApp',
      faq: 'FAQ Assistant',
      assistantTitle: 'Foundation Assistant',
      assistantStatus: 'Online for quick guidance',
      assistantClose: 'Close assistant',
      assistantCopy: 'Ask what the foundation does, how to donate, how to volunteer, or use one of the quick topic buttons below.',
      assistantInput: 'Ask a question...',
      assistantInputLabel: 'Ask the foundation assistant a question',
      send: 'Send',
      contactFoundation: 'Contact the Foundation',
      openWhatsapp: 'Open WhatsApp',
      viewPrograms: 'View Programs',
      goToDonate: 'Go to Donate',
      getInvolved: 'Get Involved',
      contactUs: 'Contact Us',
      topicWhatWeDo: 'What we do',
      topicDonate: 'How to donate',
      topicVolunteer: 'How to volunteer',
      topicContact: 'Contact details',
      topicFaq: 'General FAQs',
      responseWhatWeDo: 'Kevin Nambam Ninmol Foundation uses basketball, mentorship, education support, and community outreach to help children and young people build confidence, make positive choices, and access opportunity.',
      responseDonate: 'You can support the foundation through one-time or monthly giving. The Donate page explains giving tiers, what each amount supports, and the payment placeholder that can later be connected to Paystack or Flutterwave.',
      responseVolunteer: 'Volunteers can support clinics, mentoring, outreach, and partnership activities. The Get Involved page explains where your time and skills can help and gives a direct route to connect with the team.',
      responseContact: 'You can reach the foundation by phone, email, WhatsApp, or through the Contact page. The site also includes the office address and an embedded map to make the location easier to find.',
      responseFaq: 'Common questions include how to support the foundation, whether organizations can partner, and how programs go beyond basketball into education, mentoring, and outreach.',
      fallback: 'I do not have a precise answer for that yet, but I can guide you to the right page or help you contact the foundation directly on WhatsApp.',
      greeting: 'Hello. I can help with what the foundation does, how to donate, how to volunteer, and other common questions.',
    },
    home: {
      title: 'Home',
      heroEyebrow: 'Kevin Nambam Ninmol Foundation',
      heroTitle: 'Empowering Youth Through Basketball, Education, and Mentorship',
      heroText: 'We help young people choose hope over fear by opening pathways to growth, confidence, and opportunity through sport, learning, and guidance.',
      heroSupport: 'Founded from lived experience and grounded in practical service, the foundation exists to help children and youth rise above limitation and pursue brighter futures.',
      donateNow: 'Donate Now',
      joinUs: 'Join Us',
      trustAction: 'Trust through action',
      trustBody: 'Rooted in lived experience, youth mentorship, and visible community engagement in Jos and beyond.',
      impactEyebrow: 'Impact Snapshot',
      impactTitle: 'A growing record of visible, community-rooted impact.',
      impactText: 'We believe trust is built through measurable work, clear purpose, and consistent presence in the lives of young people.',
      aboutEyebrow: 'About Preview',
      aboutTitle: 'A personal story transformed into a public mission.',
      aboutText: 'Kevin Nambam Ninmol Foundation grew from a journey marked by hardship, resilience, and the life-changing power of opportunity.',
      aboutCopy: "From a difficult beginning to national and international basketball opportunities, Kevin's experience now fuels a foundation committed to helping young people find hope, structure, and support for the future.",
      aboutCta: 'Learn More About Us',
      programsEyebrow: 'Programs',
      programsTitle: 'Focused programs that support learning, guidance, and youth development.',
      programsText: 'Each program area is designed to respond to real needs with practical support and long-term encouragement.',
      programsCta: 'Explore All Programs',
      featuredEyebrow: 'Featured Video',
      featuredTitle: 'See the mission in motion.',
      featuredText: "Real footage from clinics and outreach helps supporters understand that the foundation's work is active, personal, and rooted in the community.",
      videoStoryLabel: 'Foundation story',
      videoClipsTitle: 'Youth impact clips',
      videoClipsText: 'Short clips from clinics and community activities help visitors feel the energy, sincerity, and consistency of the work.',
      testimonialsEyebrow: 'Testimonials',
      testimonialsTitle: 'Stories that reflect hope, growth, and real support.',
      testimonialsText: 'These short beneficiary-style stories help visitors understand how the foundation is experienced on the ground.',
      partnersEyebrow: 'Partners & Supporters',
      partnersTitle: 'Working together to expand our impact',
      partnersText: 'The foundation grows through collaboration with schools, communities, organizations, and supporters who help make youth-focused change more practical and sustainable.',
      actionEyebrow: 'Take Action',
      actionTitle: 'Partner with us to expand hope, opportunity, and youth development.',
      actionText: 'Your donations, partnerships, and support help strengthen education access, mentoring, and practical development opportunities for young people.',
      latestActivitiesEyebrow: 'Latest Activities',
      latestActivitiesTitle: 'Live updates from outreach, mentoring, and community work.',
      latestActivitiesText: 'These recent activity snapshots show that the foundation is active, consistent, and present in the lives of the young people it serves.',
      latestUpdatesEyebrow: 'Latest Updates',
      latestUpdatesTitle: 'Recent activities and updates from the field.',
      latestUpdatesText: 'Current updates help donors, partners, and visitors see that the work is active, transparent, and ongoing.',
      newsCta: 'Visit News Page',
      programLearnMore: 'Learn more',
      heroTrustSignals: ['Trusted by communities', 'Visible outreach and local partnerships', 'Transparent, mission-led delivery'],
    },
    donatePage: {
      title: 'Donate',
      heroEyebrow: 'Donate',
      heroTitle: 'Your support creates real change',
      heroSubtitle: 'This giving page is designed to make donating simple, clear, and trustworthy for every supporter.',
      giveEyebrow: 'Give Today',
      giveTitle: 'Choose how you want to support the mission.',
      giveText: 'Your gift helps the foundation respond to practical needs through youth support, educational access, mentoring, and development initiatives across local and international giving options.',
      oneTime: 'One-time donation',
      monthly: 'Monthly donation',
      chooseCurrency: 'Choose your currency',
      currencyText: 'Base donation amounts are set in NGN and displayed automatically in your selected currency.',
      customPlaceholder: 'Enter custom amount',
      customLabel: 'Custom donation amount',
      secureTitle: 'Secure payment options',
      secureText: 'Paystack or Flutterwave can be connected here for secure one-time and monthly donations.',
      conversionNote: 'Approximate conversion:',
      transparencyEyebrow: 'Transparency',
      transparencyTitle: 'Where your money goes',
      transparencyBody: 'Every contribution is used responsibly to create measurable impact. Donations help fund direct youth support, educational materials, mentoring activities, outreach delivery, and practical development programs.',
      transparencyStatement: 'The foundation is committed to transparent stewardship so donors can understand how support is translated into practical work.',
      donorEyebrow: 'Donor Assurance',
      donorTitle: 'Giving should feel clear, secure, and trustworthy.',
      donorBody: 'The foundation is committed to responsible stewardship, clear communication, and transparent use of resources so supporters can give with confidence.',
      donorReassurance: 'Every contribution is used responsibly to create measurable impact.',
      paymentNote: 'Payment gateway placeholder: Paystack / Flutterwave',
      ctaEyebrow: 'Donate',
      ctaTitle: 'Your support creates real change',
      ctaText: 'Every donation helps extend opportunity, guidance, and practical support to young people who need it most.',
      giveNow: 'Give Now',
      donateNow: 'Donate Now',
      placeholderAlert: 'Secure payment integration placeholder.',
    },
  },
  fr: {
    nav: {
      home: 'Accueil',
      about: 'A propos',
      leadership: 'Direction',
      policies: 'Politiques',
      programs: 'Programmes',
      impact: 'Impact',
      getInvolved: "S'impliquer",
      donate: 'Faire un don',
      news: 'Actualites',
      events: 'Evenements',
      contact: 'Contact',
    },
    ui: {
      menu: 'Menu',
      more: 'Plus',
      english: 'EN',
      french: 'FR',
      donate: 'Faire un don',
      lightMode: 'Mode clair',
      darkMode: 'Mode sombre',
      switchToLight: 'Passer au mode clair',
      switchToDark: 'Passer au mode sombre',
      learnMore: 'En savoir plus',
      comingSoon: 'Bientot disponible',
    },
    footer: {
      text: 'Une fondation tournee vers la jeunesse qui utilise le sport, l education, le mentorat et l appui communautaire pour construire des avenirs courageux.',
      explore: 'Explorer',
      contact: 'Contact',
      email: 'Email',
      phone: 'Telephone',
      address: 'Adresse',
      copyright: 'Copyright (c) 2026 Kevin Nambam Ninmol Foundation. Tous droits reserves.',
    },
    newsletter: {
      eyebrow: 'Newsletter',
      title: 'Restez informe de notre impact.',
      body: 'Inscrivez-vous a notre liste email pour recevoir des histoires, des mises a jour de programmes, des activites recentes et des occasions de soutenir le travail de la fondation.',
      note: 'Construisez avec nous sur le long terme grace a des nouvelles qui montrent ou le soutien fait la difference.',
      placeholder: 'Entrez votre adresse email',
      subscribe: "S'abonner",
      emailLabel: 'Adresse email',
      empty: 'Veuillez entrer votre adresse email.',
      success: "Merci. Votre inscription a la newsletter a ete enregistree dans ce flux de demonstration et peut maintenant etre reliee a un systeme d emailing en direct.",
    },
    credibility: {
      eyebrow: 'Credibilite et transparence',
      title: 'Concu pour inspirer confiance aux donateurs, partenaires et institutions.',
      body: 'La fondation s engage en faveur de la transparence, de la responsabilite, d une gestion ethique et de pratiques de sauvegarde responsables a mesure que son travail grandit.',
      trust: 'Appuyee par les communautes et renforcee par un service visible, des partenariats concrets et une gestion responsable.',
      cta: 'En savoir plus sur notre gouvernance',
    },
    floating: {
      whatsapp: 'Chat WhatsApp',
      whatsappAria: 'Discuter avec Kevin Nambam Ninmol Foundation sur WhatsApp',
      faq: 'Assistant FAQ',
      assistantTitle: 'Assistant de la fondation',
      assistantStatus: 'En ligne pour une aide rapide',
      assistantClose: "Fermer l assistant",
      assistantCopy: 'Demandez ce que fait la fondation, comment faire un don, comment devenir benevole, ou utilisez les boutons de sujets rapides ci-dessous.',
      assistantInput: 'Posez une question...',
      assistantInputLabel: "Posez une question a l assistant de la fondation",
      send: 'Envoyer',
      contactFoundation: 'Contacter la fondation',
      openWhatsapp: 'Ouvrir WhatsApp',
      viewPrograms: 'Voir les programmes',
      goToDonate: 'Aller au don',
      getInvolved: "S impliquer",
      contactUs: 'Nous contacter',
      topicWhatWeDo: 'Ce que nous faisons',
      topicDonate: 'Comment donner',
      topicVolunteer: 'Comment devenir benevole',
      topicContact: 'Coordonnees',
      topicFaq: 'FAQs generales',
      responseWhatWeDo: 'Kevin Nambam Ninmol Foundation utilise le basketball, le mentorat, le soutien educatif et les actions communautaires pour aider les enfants et les jeunes a developper leur confiance, faire des choix positifs et acceder a des opportunites.',
      responseDonate: 'Vous pouvez soutenir la fondation par des dons ponctuels ou mensuels. La page Don explique les paliers de contribution, ce que chaque montant soutient et l espace de paiement qui pourra ensuite etre connecte a Paystack ou Flutterwave.',
      responseVolunteer: "Les benevoles peuvent soutenir les cliniques, le mentorat, les actions de terrain et les activites de partenariat. La page S impliquer explique ou votre temps et vos competences peuvent aider.",
      responseContact: 'Vous pouvez joindre la fondation par telephone, email, WhatsApp ou via la page Contact. Le site comprend aussi l adresse du bureau et une carte integree.',
      responseFaq: 'Les questions courantes portent sur la maniere de soutenir la fondation, la possibilite de partenariat pour les organisations et la facon dont les programmes vont au dela du basketball vers l education, le mentorat et les actions de terrain.',
      fallback: 'Je n ai pas encore de reponse precise a cela, mais je peux vous guider vers la bonne page ou vous aider a contacter directement la fondation sur WhatsApp.',
      greeting: 'Bonjour. Je peux vous aider a comprendre ce que fait la fondation, comment faire un don, comment devenir benevole et repondre aux questions courantes.',
    },
    home: {
      title: 'Accueil',
      heroEyebrow: 'Kevin Nambam Ninmol Foundation',
      heroTitle: 'Donner aux jeunes les moyens d agir grace au basketball, a l education et au mentorat',
      heroText: 'Nous aidons les jeunes a choisir l espoir plutot que la peur en ouvrant des voies vers la croissance, la confiance et les opportunites par le sport, l apprentissage et l accompagnement.',
      heroSupport: 'Fondee sur une experience vecue et ancree dans un service concret, la fondation existe pour aider les enfants et les jeunes a depasser les limites et a poursuivre un avenir meilleur.',
      donateNow: 'Faire un don',
      joinUs: 'Nous rejoindre',
      trustAction: 'La confiance par l action',
      trustBody: 'Ancree dans l experience vecue, le mentorat des jeunes et un engagement communautaire visible a Jos et au dela.',
      impactEyebrow: 'Apercu de l impact',
      impactTitle: 'Un bilan croissant d impact visible et ancre dans la communaute.',
      impactText: 'Nous croyons que la confiance se construit par un travail mesurable, une vision claire et une presence constante dans la vie des jeunes.',
      aboutEyebrow: 'Apercu',
      aboutTitle: 'Une histoire personnelle transformee en mission publique.',
      aboutText: 'Kevin Nambam Ninmol Foundation est nee d un parcours marque par les difficultes, la resilience et le pouvoir transformateur des opportunites.',
      aboutCopy: "D un debut difficile a des opportunites nationales et internationales dans le basketball, l experience de Kevin alimente aujourd hui une fondation engagee a aider les jeunes a trouver l espoir, la structure et le soutien pour l avenir.",
      aboutCta: 'En savoir plus sur nous',
      programsEyebrow: 'Programmes',
      programsTitle: 'Des programmes cibles qui soutiennent l apprentissage, l accompagnement et le developpement des jeunes.',
      programsText: 'Chaque domaine de programme est concu pour repondre a des besoins reels avec un soutien pratique et un encouragement sur le long terme.',
      programsCta: 'Explorer tous les programmes',
      featuredEyebrow: 'Video mise en avant',
      featuredTitle: 'Voyez la mission en mouvement.',
      featuredText: 'Des images reelles des cliniques et des actions de terrain aident les soutiens a comprendre que le travail de la fondation est actif, personnel et enracine dans la communaute.',
      videoStoryLabel: 'Histoire de la fondation',
      videoClipsTitle: 'Clips d impact jeunesse',
      videoClipsText: 'De courts clips des cliniques et des activites communautaires aident les visiteurs a ressentir l energie, la sincerite et la regularite du travail.',
      testimonialsEyebrow: 'Temoignages',
      testimonialsTitle: 'Des histoires qui refletent l espoir, la croissance et un vrai soutien.',
      testimonialsText: 'Ces courts temoignages de beneficiaires aident les visiteurs a comprendre comment la fondation est vecue sur le terrain.',
      partnersEyebrow: 'Partenaires et soutiens',
      partnersTitle: 'Travailler ensemble pour elargir notre impact',
      partnersText: 'La fondation grandit grace a la collaboration avec les ecoles, les communautes, les organisations et les soutiens qui rendent le changement en faveur des jeunes plus concret et durable.',
      actionEyebrow: 'Passer a l action',
      actionTitle: 'Partenaires avec nous pour elargir l espoir, les opportunites et le developpement des jeunes.',
      actionText: 'Vos dons, partenariats et soutiens aident a renforcer l acces a l education, le mentorat et les possibilites concretes de developpement pour les jeunes.',
      latestActivitiesEyebrow: 'Dernieres activites',
      latestActivitiesTitle: 'Des nouvelles en direct des actions de terrain, du mentorat et du travail communautaire.',
      latestActivitiesText: 'Ces instantanes recents montrent que la fondation est active, constante et presente dans la vie des jeunes qu elle accompagne.',
      latestUpdatesEyebrow: 'Dernieres mises a jour',
      latestUpdatesTitle: 'Activites et nouvelles recentes du terrain.',
      latestUpdatesText: 'Les mises a jour actuelles aident les donateurs, partenaires et visiteurs a voir que le travail est actif, transparent et continu.',
      newsCta: 'Voir la page Actualites',
      programLearnMore: 'En savoir plus',
      heroTrustSignals: ['Appuyee par les communautes', 'Actions visibles et partenariats locaux', 'Mise en oeuvre transparente et guidee par la mission'],
    },
    donatePage: {
      title: 'Faire un don',
      heroEyebrow: 'Faire un don',
      heroTitle: 'Votre soutien cree un changement reel',
      heroSubtitle: 'Cette page de don est concue pour rendre la contribution simple, claire et digne de confiance pour chaque soutien.',
      giveEyebrow: 'Donnez aujourd hui',
      giveTitle: 'Choisissez comment soutenir la mission.',
      giveText: 'Votre don aide la fondation a repondre a des besoins concrets a travers le soutien a la jeunesse, l acces a l education, le mentorat et les initiatives de developpement, localement et a l international.',
      oneTime: 'Don ponctuel',
      monthly: 'Don mensuel',
      chooseCurrency: 'Choisissez votre devise',
      currencyText: 'Les montants de base sont definis en NGN et s affichent automatiquement dans la devise choisie.',
      customPlaceholder: 'Entrez un montant personnalise',
      customLabel: 'Montant de don personnalise',
      secureTitle: 'Options de paiement securisees',
      secureText: 'Paystack ou Flutterwave peuvent etre connectes ici pour des dons ponctuels et mensuels securises.',
      conversionNote: 'Conversion approximative :',
      transparencyEyebrow: 'Transparence',
      transparencyTitle: 'A quoi sert votre don',
      transparencyBody: 'Chaque contribution est utilisee de maniere responsable pour creer un impact mesurable. Les dons financent le soutien direct aux jeunes, le materiel educatif, le mentorat, les actions de terrain et les programmes de developpement.',
      transparencyStatement: 'La fondation s engage a une gestion transparente afin que les donateurs puissent comprendre comment le soutien se transforme en actions concretes.',
      donorEyebrow: 'Assurance donateur',
      donorTitle: 'Donner doit etre clair, sur et digne de confiance.',
      donorBody: 'La fondation s engage en faveur d une gestion responsable, d une communication claire et d un usage transparent des ressources afin que les soutiens puissent donner en toute confiance.',
      donorReassurance: 'Chaque contribution est utilisee de maniere responsable pour creer un impact mesurable.',
      paymentNote: 'Passerelle de paiement placeholder : Paystack / Flutterwave',
      ctaEyebrow: 'Faire un don',
      ctaTitle: 'Votre soutien cree un changement reel',
      ctaText: 'Chaque don aide a elargir les opportunites, l accompagnement et le soutien concret aux jeunes qui en ont le plus besoin.',
      giveNow: 'Donner maintenant',
      donateNow: 'Faire un don',
      placeholderAlert: 'Integration securisee du paiement en cours.',
    },
  },
};

const LanguageContext = createContext(null);

function getValue(obj, path) {
  return path.split('.').reduce((current, key) => current?.[key], obj);
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'en');

  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem('language', language);
  }, [language]);

  const value = useMemo(() => {
    const t = (path) => getValue(translations[language], path) ?? getValue(translations.en, path) ?? path;
    return { language, setLanguage, t };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
